Repository coffee-tools/coffee, pull requests merged in 2023-05, with the labels that each got.

#133 fix(core): allow dirty state for add remote
  coffee_core/src/coffee.rs
Labels: 🐛 - bug

#132 feat(coffee): implement upgrade command
  coffee_cmd/src/cmd.rs
  coffee_cmd/src/main.rs
  coffee_core/src/coffee.rs
  coffee_core/src/lib.rs
  coffee_github/src/repository.rs
  coffee_github/src/utils.rs
  coffee_lib/src/plugin_manager.rs
  coffee_lib/src/repository.rs
  coffee_lib/src/types/mod.rs
  coffee_storage/src/model/repository.rs
  docs/docs-book/src/using-coffee.md
Labels: enhancement, 💭 - brainstorming, 🎯 - triage

#134 feat(httpd): implement list call
  Cargo.lock
  coffee_httpd/Cargo.toml
  coffee_httpd/src/httpd/server.rs
Labels: enhancement, ❤️ - SoB
